
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: knowledge_canvasser_development

test:
  <<: *default
  database: knowledge_canvasser_test

production:
  <<: *default
  database: knowledge_canvasser_production
  username: knowledge_canvasser
  password: <%= ENV['KNOWLEDGE_CANVASSER_DATABASE_PASSWORD'] %>
